# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt)
#
# Copyright Rene Rivera 2020.

# Configuration for https://cirrus-ci.org/.

linux_task:
  # All the GCC's and Clang's available for Ubuntu Bionic.
  matrix:
    - { name: 'Linux, GCC 10', env: { CXX: g++-10, PACKAGES: g++-10 }, container: { image: 'ubuntu:18.04' } }
    - { name: 'Linux, GCC 9', env: { CXX: g++-9, PACKAGES: g++-9 }, container: { image: 'ubuntu:18.04' } }
    - { name: 'Linux, Clang 10', env: { CXX: clang-10, PACKAGES: clang-10, LLVM_OS: bionic, LLVM_VER: 10 }, container: { image: 'ubuntu:18.04' } }
    - { name: 'Linux, Clang 9', env: { CXX: clang-9, PACKAGES: clang-9, LLVM_OS: bionic, LLVM_VER: 9 }, container: { image: 'ubuntu:18.04' } }
  # Need some extra container setup.
  setup_script: [
    "apt-get -o Acquire::Retries=3 update && apt-get -o Acquire::Retries=3 install -y sudo software-properties-common wget apt-transport-https && rm -rf /var/lib/apt/lists/*"
    ]
  # The install runs a helper script to do the install and any setup.
  install_script: [
    "echo '==================================> INSTALL TOOLSET'",
    "uname -a",
    "./.ci_playground/linux-cxx-install.sh"
    ]
  compile_script: [
    "${CXX} --version",
    "${CXX} ${CXXFLAGS} -v src/main.cpp"
    ]
