# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2020.

branches:
  only:
    - /master.*/

skip_commits:
 files:
   - .circleci/*
   - azure-pipelines.yml
   - .semaphore/*

platform:
  - x86
  - x64

environment:
  matrix:
  - job_name: 'VS 2019'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    VSWHERE_VERSION: '[16.0,17.0)'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2017'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VSWHERE_VERSION: '[15.0,16.0)'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2015'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VCVARSALL: '$(VS140COMNTOOLS)..\..\VC\vcvarsall.bat'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2013'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VCVARSALL: '$(VS120COMNTOOLS)..\..\VC\vcvarsall.bat'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2012'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VCVARSALL: '$(VS110COMNTOOLS)..\..\VC\vcvarsall.bat'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2010'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VCVARSALL: '$(VS100COMNTOOLS)..\..\VC\vcvarsall.bat'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc

matrix:
  exclude:
    - job_name: 'VS 2012'
      platform: x64
    - job_name: 'VS 2010'
      platform: x64

before_build:
  - ps: |
      ">>>>>"
      ">>>>> INSTALL TOOLSET .."
      ">>>>>"
      if ($env:CHOCO_VS_PACKAGE) {
        choco install $env:CHOCO_VS_PACKAGE -packageParameters "--AdminFile .ci_playground/$env:CHOCO_VS_PACKAGE.xml"
      }
      choco install vswhere

build_script:
  - ps: |
      ">>>>>"
      ">>>>> COMPILE, Setup .."
      ">>>>>"
      if ($env:VSWHERE_LEGACY) {
        $installationPath = vswhere -legacy -latest -property installationPath -version "$env:VSWHERE_LEGACY"
        if ($installationPath) { $env:VCVARSALL = "$installationPath\VC\vcvarsall.bat" }
      }
      if ($env:VSWHERE_VERSION) {
        $installationPath = vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -version "$env:VSWHERE_VERSION"
        if ($installationPath) { $env:VCVARSALL = "$installationPath\VC\Auxiliary\Build\vcvarsall.bat" }
      }
      if ($env:VCVARSALL) { $SETUP = "$env:VCVARSALL", "$env:PLATFORM" }
      if (!($SETUP)) { $SETUP = $env:SETUP }
      if (!($SETUP)) { $SETUP = "Write-Output", "No setup available" }
      & "$SETUP[0]" $SETUP[1..-1]
      ">>>>>"
      ">>>>> COMPILE .."
      ">>>>>"
      & $env:CXX $env:CXXFLAGS src/main.cpp
