# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2020.

branches:
  only:
    - /master.*/

skip_commits:
 files:
   - '.circleci/*'
   - azure-pipelines.yml

platform:
  - x86
  - x64

environment:
  matrix:
  - job_name: 'VS 2017'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    SETUPXX: '"%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -version "[15.0,16.0)"'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2015'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    SETUPXX: '"$(VS140COMNTOOLS)..\..\VC\vcvarsall.bat" $(PLATFORM)'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2013'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    SETUPXX: '"$(VS120COMNTOOLS)..\..\VC\vcvarsall.bat" $(PLATFORM)'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2012'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    SETUPXX: '"$(VS110COMNTOOLS)..\..\VC\vcvarsall.bat" $(PLATFORM)'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2010'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    SETUPXX: '"$(VS100COMNTOOLS)..\..\VC\vcvarsall.bat" $(PLATFORM)'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc

matrix:
  exclude:
    - job_name: 'VS 2012'
      platform: x64
    - job_name: 'VS 2010'
      platform: x64

before_build:
  - cmd: |
      @echo off
      echo ">>>>>"
      echo ">>>>> INSTALL TOOLSET, Setup .."
      echo ">>>>>"
      %SETUPXX%

build_script:
  - cmd: |
      @echo off
      echo ">>>>>"
      echo ">>>>> COMPILE .."
      echo ">>>>>"
      "%CXX%" %CXXFLAGS% src/main.cpp
