# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2020.

branches:
  only:
    - /master.*/

skip_commits:
 files:
   - '.circleci/*'
   - azure-pipelines.yml

platform:
  - x86
  - x64

environment:
  matrix:
  - job_name: 'VS 2017'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PATH: '$(ProgramFiles)\Microsoft Visual Studio\Installer;$(PATH)'
    VSWHERE_VERSION: '[15.0,16.0)'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2015'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VCVARSALL: '$(VS140COMNTOOLS)..\..\VC\vcvarsall.bat'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2013'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VCVARSALL: '$(VS120COMNTOOLS)..\..\VC\vcvarsall.bat'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2012'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VCVARSALL: '$(VS110COMNTOOLS)..\..\VC\vcvarsall.bat'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc
  - job_name: 'VS 2010'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VCVARSALL: '$(VS100COMNTOOLS)..\..\VC\vcvarsall.bat'
    CXX: cl.exe
    CXXFLAGS: /Zi /MT /TP /Femain /Ox /GL /EHsc

matrix:
  exclude:
    - job_name: 'VS 2012'
      platform: x64
    - job_name: 'VS 2010'
      platform: x64

before_build:
  - cmd: |
      set
      echo ">>>>>"
      echo ">>>>> INSTALL TOOLSET, Setup .."
      echo ">>>>>"
      if not "%VSWHERE_VERSION%"=="" ( for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -version "%VSWHERE_VERSION%"`) do ( set "VCVARSALL=%%i\VC\Auxiliary\Build\vcvarsall.bat" ) )
      if not "%VCVARSALL%"=="" ( "%VCVARSALL%" %PLATFORM% )

build_script:
  - cmd: |
      set
      echo ">>>>>"
      echo ">>>>> COMPILE .."
      echo ">>>>>"
      "%CXX%" %CXXFLAGS% src/main.cpp
