# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2020.

branches:
  only:
    - /master.*/

environment:
  matrix:
  - job_name: 'VS 2015'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    SETUPXX: $(VS140COMNTOOLS)..\..\VC\vcvarsall.bat
    CXX: cl.exe
    CXXFLAGS: /nologo /Zi /MT /TP /Feb2 /Ox /GL /EHsc
    CXXINFO: cl.exe /?
  - job_name: 'VS 2013'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    SETUPXX: $(VS120COMNTOOLS)..\..\VC\vcvarsall.bat
    CXX: cl.exe
    CXXFLAGS: /nologo /Zi /MT /TP /Feb2 /Ox /GL /EHsc
    CXXINFO: cl.exe /?
  - job_name: 'VS 2012'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    SETUPXX: $(VS110COMNTOOLS)..\..\VC\vcvarsall.bat
    CXX: cl.exe
    CXXFLAGS: /nologo /Zi /MT /TP /Feb2 /Ox /GL /EHsc
    CXXINFO: cl.exe /?
  - job_name: 'VS 2010'
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    SETUPXX: $(VS100COMNTOOLS)..\..\VC\vcvarsall.bat
    CXX: cl.exe
    CXXFLAGS: /nologo /Zi /MT /TP /Feb2 /Ox /GL /EHsc
    CXXINFO: cl.exe /?

before_build:
  - cmd: |
      @echo off
      echo ">>>>>"
      echo ">>>>> INSTALL TOOLSET, Setup .."
      echo ">>>>>"
      "%SETUPXX%"
      echo ">>>>>"
      echo ">>>>> INSTALL TOOLSET, Info .."
      echo ">>>>>"
      "%CXXINFO%" 

build_script:
  - cmd: |
      @echo off
      echo ">>>>>"
      echo ">>>>> COMPILE .."
      echo ">>>>>"
      "%CXX%" %CXXFLAGS% src/main.cpp

