# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2020.

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - .circleci/*
    - appveyor.yml

stages:

- stage: Test
  jobs:

  - job: 'Linux'
    strategy:
      matrix:
        GCC 9:
          CXX: g++-9
          PACKAGES: g++-9
          VM_IMAGE: 'ubuntu-18.04'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - bash: |
        set -e
        uname -a
        ./.ci_playground/linux-cxx-install.sh
      displayName: Install Toolset
    - bash: |
        set -e
        ${CXX} --version
        ${CXX} src/main.cpp
      displayName: Compile

  - job: 'macOS'
    strategy:
      matrix:
        Xcode 11.4:
          CXX: clang++
          VM_IMAGE: 'macOS-10.15'
          XCODE_VERSION: 11.4
        Xcode 9.4.1:
          CXX: clang++
          VM_IMAGE: 'macOS-10.14'
          XCODE_VERSION: 9.4.1
          MACOSX_DEPLOYMENT_TARGET: 10.13
          CXXFLAGS: -v
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - bash: |
        set -e
        uname -a
        export 'XCODE_INSTALL_USER=$(DEV_APPLE_USER)'
        export 'XCODE_INSTALL_PASSWORD=$(DEV_APPLE_PASSWORD)'
        ./.ci_playground/macos-xcode-install.sh
        sudo find / -name "*.sdk" -print
      displayName: Install Toolset
    - bash: |
        set -e
        ${CXX} --version
        ${CXX} ${CXXFLAGS} src/main.cpp
      displayName: Compile
