# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt)
#
# Copyright Rene Rivera 2020.

# Configuration for https://azure.microsoft.com/en-us/services/devops/pipelines/.

trigger:
  # We limit when to run the builds to specific branches.
  branches:
    include:
    - master
  # And also limit to avoid building when CI files from other services change.
  paths:
    exclude:
    - .circleci/*
    - .cirrus.yml
    - .drone.star
    - .github/workflows/*
    - .semaphore/*
    - .travis.yml
    - appveyor.yml

# There are many arrangements possible with Azure Pipelines stages. But our
# experimental needs are rather simple. Hence we only have a single stage
# to do our test builds in.

stages:

- stage: Test
  jobs:

  # We group the jobs based on platform as the scripts are usually specific
  # to the platform and not the compiler.
  - job: 'Linux'
    strategy:
      matrix:
        GCC 10: { CXX: g++-10, PACKAGES: g++-10, VM_IMAGE: 'ubuntu-18.04' }
        GCC 9: { CXX: g++-9, PACKAGES: g++-9, VM_IMAGE: 'ubuntu-18.04' }
        GCC 8: { CXX: g++-8, PACKAGES: g++-8, VM_IMAGE: 'ubuntu-18.04' }
        GCC 7: { CXX: g++-7, PACKAGES: g++-7, VM_IMAGE: 'ubuntu-18.04' }
        GCC 6: { CXX: g++-6, PACKAGES: g++-6, VM_IMAGE: 'ubuntu-18.04' }
        GCC 5: { CXX: g++-5, PACKAGES: g++-5, VM_IMAGE: 'ubuntu-18.04' }
        Clang 11: { CXX: clang-11, PACKAGES: clang-11, LLVM_OS: bionic, LLVM_VER: 11, VM_IMAGE: 'ubuntu-18.04' }
        Clang 10: { CXX: clang-10, PACKAGES: clang-10, LLVM_OS: bionic, LLVM_VER: 10, VM_IMAGE: 'ubuntu-18.04' }
        Clang 9: { CXX: clang-9, PACKAGES: clang-9, LLVM_OS: bionic, LLVM_VER: 9, VM_IMAGE: 'ubuntu-18.04' }
        Clang 8: { CXX: clang-8, PACKAGES: clang-8, LLVM_OS: bionic, LLVM_VER: 8, VM_IMAGE: 'ubuntu-18.04' }
        Clang 7: { CXX: clang-7, PACKAGES: clang-7, LLVM_OS: bionic, LLVM_VER: 7, VM_IMAGE: 'ubuntu-18.04' }
        Clang 6.0: { CXX: clang-6.0, PACKAGES: clang-6.0, LLVM_OS: bionic, LLVM_VER: 6.0, VM_IMAGE: 'ubuntu-18.04' }
        Clang 5.0: { CXX: clang-5.0, PACKAGES: clang-5.0, LLVM_OS: bionic, LLVM_VER: 5.0, VM_IMAGE: 'ubuntu-18.04' }
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    # Two simple steps.. The install runs a helper script to do the install
    # and any setup.
    - bash: |
        set -e
        uname -a
        ./.ci_playground/linux-cxx-install.sh
      displayName: Install Toolset
    # And the compiler step just calls the compiler as specified in the
    # matrix.
    - bash: |
        set -e
        ${CXX} --version
        ${CXX} ${CXXFLAGS} -v src/main.cpp
      displayName: Compile

  - job: 'macOS'
    strategy:
      matrix:
        Xcode 12.2: { CXX: clang++, VM_IMAGE: 'macOS-10.15', XCODE_VERSION: 12.2 }
        Xcode 12.0: { CXX: clang++, VM_IMAGE: 'macOS-10.15', XCODE_VERSION: 12.0 }
        Xcode 11.7: { CXX: clang++, VM_IMAGE: 'macOS-10.15', XCODE_VERSION: 11.7 }
        Xcode 11.6: { CXX: clang++, VM_IMAGE: 'macOS-10.15', XCODE_VERSION: 11.6 }
        Xcode 11.5: { CXX: clang++, VM_IMAGE: 'macOS-10.15', XCODE_VERSION: 11.5 }
        Xcode 11.4.1: { CXX: clang++, VM_IMAGE: 'macOS-10.15', XCODE_VERSION: 11.4.1 }
        Xcode 11.3.1: { CXX: clang++, VM_IMAGE: 'macOS-10.15', XCODE_VERSION: 11.3.1 }
        Xcode 11.2.1: { CXX: clang++, VM_IMAGE: 'macOS-10.15', XCODE_VERSION: 11.2.1 }
        Xcode 11.1: { CXX: clang++, VM_IMAGE: 'macOS-10.15', XCODE_VERSION: 11.1 }
        Xcode 10.3: { CXX: clang++, VM_IMAGE: 'macOS-10.14', XCODE_VERSION: 10.3 }
        Xcode 10.2.1: { CXX: clang++, VM_IMAGE: 'macOS-10.14', XCODE_VERSION: 10.2.1 }
        Xcode 10.1: { CXX: clang++, VM_IMAGE: 'macOS-10.14', XCODE_VERSION: 10.1 }
        Xcode 9.4.1: { CXX: clang++, VM_IMAGE: 'macOS-10.14', XCODE_VERSION: 9.4.1 }

    pool:
      vmImage: $(VM_IMAGE)
    steps:
    # The setup step on macOS includes reflecting the Apple developer
    # credentials to the install script.
    - bash: |
        set -e
        uname -a
        export 'XCODE_INSTALL_USER=$(DEV_APPLE_USER)'
        export 'XCODE_INSTALL_PASSWORD=$(DEV_APPLE_PASSWORD)'
        ./.ci_playground/macos-xcode-install.sh
      displayName: Install Toolset
    # For consistent Xcode building we specify the sysroot to point to the
    # symlink that xcode-install utility created. This was we always build
    # with the specific SDK for the compiler being used.
    - bash: |
        set -e
        ${CXX} --version
        ${CXX} ${CXXFLAGS} -v --sysroot "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" src/main.cpp
      displayName: Compile

  - job: 'Windows'
    strategy:
      matrix:
        VS 2019:
          VSWHERE_VERSION: '[16.0,17.0)'
          CXX: cl.exe
          CXXFLAGS: /Femain
          PLATFORM: x64
          VM_IMAGE: 'windows-2019'
        VS 2017:
          VSWHERE_VERSION: '[15.0,16.0)'
          CXX: cl.exe
          CXXFLAGS: /Femain
          PLATFORM: x64
          VM_IMAGE: 'vs2017-win2016'
        # Installing VS in general takes forever. But this is here as an
        # example of what to specify for using choco to install VS.
        # VS 2015:
        #   VSWHERE_LEGACY: '[14.0,15.0)'
        #   CXX: cl.exe
        #   CXXFLAGS: /Femain
        #   PLATFORM: x64
        #   CHOCO_VS_PACKAGE: VisualStudio2015Community
        #   VM_IMAGE: 'windows-latest'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    # For Visual Studio it's usually already install in CI. Which means that
    # we usually don't need to install it. But in case we do we can use
    # choco to do this.
    - script: |
        echo ">>>>>"
        echo ">>>>> INSTALL TOOLSET .."
        echo ">>>>>"
        if not "%CHOCO_VS_PACKAGE%"=="" choco install %CHOCO_VS_PACKAGE% -packageParameters "--AdminFile .ci_playground/%CHOCO_VS_PACKAGE%.xml"
        choco install vswhere
      displayName: Install
    # To compile we need to set up the CLI environment using the vcvarsall.bat
    # script provided by Visual Studio.
    - script: |
        echo ">>>>>"
        echo ">>>>> COMPILE, Setup .."
        echo ">>>>>"
        .ci_playground/windows-msvc-setup.cmd
        echo ">>>>>"
        echo ">>>>> COMPILE .."
        echo ">>>>>"
        "%CXX%" %CXXFLAGS% src/main.cpp
      displayName: Compile
