# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2020.

version: 2.1
jobs:
  linux-job:
    parameters:
      image:
        default: "ubuntu-1604:201903-01"
        type: string
      llvm_repo:
        default: ""
        type: string
      cxx:
        default: "c++"
        type: string
      packages:
        default: ""
        type: string
    machine:
      image: << parameters.image >>
    environment:
      LLVM_REPO: << parameters.llvm_repo >>
      CXX: << parameters.cxx >>
      PACKAGES: << parameters.packages >>
    steps:
      - checkout
      - run:
          name: Install Toolset
          command: |
            set -e
            uname -a
            ./.ci_playground/linux-cxx-install.sh
      - run:
          name: Compile
          command: |
            set -e
            ${CXX} --version
            ${CXX} src/main.cpp
workflows:
  workflow:
    jobs:
      - linux-job:
          name: 'Linux GCC 9'
          cxx: g++-9
          packages: g++-9
      - linux-job:
          name: 'Linux GCC 8'
          cxx: g++-8
          packages: g++-8
